version: '2'
services:
  web:
    build: .
    command: bundle exec rails s -p3000 -b 0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    volumes_from:
      - bundle
  bundle:
    image: devrailsondocker_web
    command: echo bundler container
    volumes:
      - /bundle
